# Generated by Django 3.2.2 on 2021-06-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя группы')),
                ('yearOfAdmissions', models.CharField(max_length=45, verbose_name='Год формирования')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('surename', models.CharField(default='', max_length=45, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default='', max_length=45, verbose_name='Отчество')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('note', models.TextField(max_length=255, verbose_name='Интересы')),
                ('admin', models.CharField(choices=[(1, 'да'), (0, 'нет')], default=0, max_length=2, verbose_name='Статус администратора')),
                ('specialist', models.CharField(choices=[(1, 'да'), (0, 'нет')], default=0, max_length=2, verbose_name='Специалист УО')),
                ('login', models.CharField(default=None, max_length=45, verbose_name='Логин')),
                ('password', models.CharField(default=None, max_length=45, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('surename', models.CharField(default='', max_length=45, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default='', max_length=45, verbose_name='Отчество')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('note', models.TextField(max_length=255, verbose_name='Интересы')),
                ('parentsArePensioners', models.CharField(choices=[(1, 'да'), (0, 'нет')], default=0, max_length=2, verbose_name='Родители пенсионеры')),
                ('amountOfChildren', models.IntegerField(default=0, verbose_name='Количество детей')),
                ('dateOfBirth', models.DateField(verbose_name='День рождения')),
                ('cityOfRegistration', models.CharField(max_length=45, verbose_name='Город прописка')),
                ('cityOfResidence', models.CharField(max_length=45, verbose_name='Город проживания')),
                ('gender', models.CharField(choices=[(1, 'м'), (0, 'ж')], max_length=2, verbose_name='Гендер')),
                ('juvenileAffairsUnit', models.CharField(choices=[(1, 'да'), (0, 'нет')], max_length=45, verbose_name='Отдел по делам несовершеннолетних')),
                ('fullFamily', models.CharField(max_length=45, verbose_name='Состав семьи')),
                ('interests', models.TextField(max_length=255, verbose_name='Интересы')),
                ('sportsSections', models.CharField(max_length=45, verbose_name='Интересы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('surename', models.CharField(default='', max_length=45, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default='', max_length=45, verbose_name='Отчество')),
                ('email', models.CharField(max_length=45, verbose_name='Email')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('note', models.TextField(max_length=255, verbose_name='Интересы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tutor'),
        ),
    ]
