# Generated by Django 3.2.2 on 2021-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
        migrations.AddField(
            model_name='parent',
            name='verify',
            field=models.TextField(default=None, null=True, verbose_name='Код верификации'),
        ),
        migrations.AddField(
            model_name='student',
            name='verify',
            field=models.TextField(default=None, null=True, verbose_name='Код верификации'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='verify',
            field=models.TextField(default=None, null=True, verbose_name='Код верификации'),
        ),
    ]
