# Generated by Django 3.2.2 on 2021-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210604_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=45, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='amountOfChildren',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullFamily',
            field=models.CharField(blank=True, max_length=45, verbose_name='Состав семьи'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.TextField(blank=True, max_length=255, verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='juvenileAffairsUnit',
            field=models.CharField(blank=True, choices=[(1, 'да'), (0, 'нет')], default=0, max_length=45, verbose_name='Отдел по делам несовершеннолетних'),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentsArePensioners',
            field=models.CharField(blank=True, choices=[(1, 'да'), (0, 'нет')], default=0, max_length=2, verbose_name='Родители пенсионеры'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=45, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sportsSections',
            field=models.CharField(blank=True, max_length=45, verbose_name='Спортивные секции'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='admin',
            field=models.CharField(blank=True, choices=[(1, 'да'), (0, 'нет')], default='нет', max_length=3, verbose_name='Статус администратора'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(blank=True, max_length=45, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='specialist',
            field=models.CharField(blank=True, choices=[(1, 'да'), (0, 'нет')], default='нет', max_length=3, verbose_name='Специалист УО'),
        ),
    ]
