# Generated by Django 3.2.2 on 2021-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210604_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='juvenileAffairsUnit',
            field=models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=45, verbose_name='Отдел по делам несовершеннолетних'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentsArePensioners',
            field=models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=45, verbose_name='Родители пенсионеры'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='admin',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=45, verbose_name='Статус администратора'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='specialist',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=45, verbose_name='Специалист УО'),
        ),
    ]
