# Generated by Django 3.2.2 on 2021-06-05 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210604_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('м', 'м'), ('ж', 'ж')], default='м', max_length=2, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='admin',
            field=models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], max_length=45, verbose_name='Статус администратора'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='specialist',
            field=models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], max_length=45, verbose_name='Специалист УО'),
        ),
    ]
