# Generated by Django 3.2.2 on 2021-06-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210605_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='yearOfAdmissions',
            new_name='year',
        ),
        migrations.AddField(
            model_name='parent',
            name='who',
            field=models.CharField(blank=True, max_length=45, verbose_name='Кем приходится'),
        ),
    ]
