# Generated by Django 3.2.2 on 2021-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210605_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='verify',
            field=models.CharField(default='complete', max_length=45, null=True, verbose_name='Верификация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='verify',
            field=models.CharField(default='complete', max_length=45, null=True, verbose_name='Верификация'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='verify',
            field=models.CharField(default='complete', max_length=45, null=True, verbose_name='Верификация'),
        ),
    ]
