# Generated by Django 3.2.2 on 2021-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210610_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='log_in',
            field=models.BooleanField(default=False, verbose_name='Пользователь авторизован'),
        ),
        migrations.AddField(
            model_name='student',
            name='log_in',
            field=models.BooleanField(default=False, verbose_name='Пользователь авторизован'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='log_in',
            field=models.BooleanField(default=False, verbose_name='Пользователь авторизован'),
        ),
    ]
